name: vault
home: https://www.vaultproject.io/
version: 0.9.1
description: Vault secures, stores, and tightly controls access to tokens, passwords, certificates, API keys, and other secrets in modern computing.
sources:
  - https://bitbucket.org/datdevops/helm-vault
