# Default values for jenkins.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Name: vault

etcd:
  Replicas: 3
  Version: 3.2.11

  Port: 2379

Image:
  Name: vault
  Tag: 0.9.1

Service:
  Type: ClusterIP

Port:
  Container: 8200
  Service: 8200

Scheduling:
  NodeSelector:

Persistence:
  Enabled: false
  StorageClass: standard
  AccessMode: ReadWriteOnce
  Size: 1Gi
  volumes:
#  - name: nothing
#    emptyDir: {}
  mounts:
#  - mountPath: /var/nothing
#    name: nothing
#    readOnly: true
